system0 {
  akka {
    loglevel = "ERROR"

    actor {
      provider = "akka.remote.RemoteActorRefProvider"
    }

    remote {
      enabled-transports = ["akka.remote.netty.tcp"]
      netty.tcp {
        hostname = "10.57.172.85"
        port = 2551
      }
    }
  }
}

system1 {
  akka {
    loglevel = "ERROR"

    actor {
      provider = "akka.remote.RemoteActorRefProvider"
    }

    remote {
      enabled-transports = ["akka.remote.netty.tcp"]
      netty.tcp {
        hostname = "10.57.172.20"
        port = 6001
      }
    }
  }
}

system2 {
  akka {
    loglevel = "ERROR"

    actor {
      provider = "akka.remote.RemoteActorRefProvider"
    }

    remote {
      enabled-transports = ["akka.remote.netty.tcp"]
      netty.tcp {
        hostname = "192.168.1.124"
        port = 2552
      }
    }
  }
}

system3 {
  akka {
    loglevel = "ERROR"

    actor {
      provider = "akka.remote.RemoteActorRefProvider"
    }

    remote {
      enabled-transports = ["akka.remote.netty.tcp"]
      netty.tcp {
        hostname = "127.0.0.1"
        port = 6003
      }
    }
  }
}
